apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xva6hl6la-nodejs 
  janus-idp.io/tekton: xva6hl6la-nodejs
  backstage.io/kubernetes-id: xva6hl6la-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xva6hl6la-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml