apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xva6hl6la-nodejs-gitops
  description: This is GitOps manifest for xva6hl6la-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=xva6hl6la-nodejs
    backstage.io/kubernetes-id: xva6hl6la-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xva6hl6la-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xva6hl6la-nodejs
