apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xva6hl6la-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xva6hl6la-nodejs 
  name: xva6hl6la-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xva6hl6la-nodejs 
